name: ARC4 compile and run

on:
  push:
    branches:
      - arc4-continuous-integration  # Set a branch name to trigger deployment

jobs:
  build:

    #runs-on: ARC4

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        source /apps/Modules/3.2.10/init/bash
        ./utils/arc/monc_compile_arc.sh
    - name: run
      run: |
        ./utils/arc/submonc.sge
